name: Test

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Generate key
              run: |
                cp .env.example .env
                php artisan key:generate

            - name: Build Assets
              run: npm ci && npm run prod

            - name: PHPUnit
              run: vendor/bin/phpunit
              env:
                GITHUB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
                GITHUB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

            - name: Integration Tests
              run: vendor/bin/phpunit tests/Integration
              env:
                GITHUB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
                GITHUB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
